import { SourceCard } from './source-card';

export const sourceCards: SourceCard[] = [
    { name: 'Duck', filename: 'pexels-francesco-altamura-7745377.jpg' },
    { name: 'Kitten', filename: 'pexels-anel-rossouw-2558605.jpg' },
    { name: 'Dogs', filename: 'pexels-sebastian-coman-travel-3448793.jpg' },
    { name: 'Lion', filename: 'pexels-frans-van-heerden-675406.jpg' },
    { name: 'Eagle', filename: 'pexels-frank-cone-3250638.jpg' },
    { name: 'Owl', filename: 'pexels-fred-zegveld-5575593.jpg' },
    { name: 'Spider', filename: 'pexels-egor-kamelev-7817534.jpg' },
    { name: 'Starfish', filename: 'pexels-mark-walz-2540698.jpg' },
    { name: 'Penguin', filename: 'pexels-pixabay-52512.jpg' },
    { name: 'Otter', filename: 'pexels-pixabay-53510.jpg' },
    { name: 'Dragonfly', filename: 'pexels-skyler-ewing-8279454.jpg' },
    { name: 'Ibex', filename: 'pexels-anna-perkas-7339122.jpg' },
    { name: 'Snail', filename: 'pexels-pixabay-53203.jpg' },
    { name: 'Kangaroo', filename: 'pexels-karolina-grabowska-5840729.jpg' },
    { name: 'Zebra', filename: 'pexels-magda-ehlers-3823003.jpg' },
    { name: 'Dolphins', filename: 'pexels-tim-hartelt-4808424.jpg' },
    { name: 'Dahlia', filename: 'pexels-gru-369433.jpg' },
    { name: 'Petunia', filename: 'pexels-ryutaro-tsukata-6249239.jpg' },
    { name: 'Marigold', filename: 'pexels-silvia-corradin-1031628.jpg' },
    { name: 'Rose', filename: 'pexels-pixabay-56866.jpg' },
    { name: 'Daylily', filename: 'pexels-samantha-diederichs-4569320.jpg' },
    { name: 'Tiger', filename: 'pexels-flickr-145939.jpg' },
    { name: 'Plumeria', filename: 'pexels-nipananlifestylecom-1424467.jpg' },
    { name: 'Gerbera', filename: 'pexels-ylanite-koppens-2343171.jpg' },
    { name: 'Zinnia', filename: 'pexels-anton-grekhov-9055685.jpg' },
    { name: 'Pansy', filename: 'pexels-plato-terentev-9811598.jpg' },
    { name: 'Tulip', filename: 'pexels-jos-van-ouwerkerk-1075959.jpg' },
    { name: 'Monitor Lizard', filename: 'pexels-erik-karits-5311748.jpg' },
    { name: 'Red Panda', filename: 'pexels-christian-krumbholz-1217595.jpg' },
    { name: 'Koala', filename: 'pexels-connor-slade-2943232.jpg' },
    { name: 'Orchid', filename: 'pexels-alyssa-polaris-7455435.jpg' },
    { name: 'Bird of Paradise', filename: 'pexels-jean-van-der-meulen-1608471.jpg' }
];
